### ISSUE TITLE
RWLock'd map deemed not linearizable

### ISSUE THREAD

**Issue by thomasjungblut** [anishathalye/porcupine#11] opened 2022-11-11 20:17 UTC
Hey @anishathalye,

Thanks for the library, we're making pretty heavy use of this now in etcd and I spent the day to play around with it and check a [toy database of mine](https://github.com/thomasjungblut/go-sstables/pull/19). 

While doing that, I came across an odd issue with `sync.RWMutex` which guards the three main operations (Get with ReadLock and Put+Delete with a WriteLock). 

From [sync.RWMutex](https://pkg.go.dev/sync#RWMutex):

> A RWMutex is a reader/writer mutual exclusion lock. The lock can be held by an arbitrary number of readers or a single writer. The zero value for a RWMutex is an unlocked mutex.
> If a goroutine holds a RWMutex for reading and another goroutine might call Lock, no goroutine should expect to be able to acquire a read lock until the initial read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock.

Given this is implemented correctly in Go (I would assume so), this should give us linearizability over concurrent map operations. A single threaded happy path test runs correctly, the multi-goroutine one sadly returns `Illegal`.

The full code can be found in this commit: https://github.com/thomasjungblut/porcupine/commit/d01d21699b74166d39f001b781767aa812fbf366

And should be reproducible with a simple `go test` on the rwlock package.

I would love to attach a better visualization of this issue, however there's some issue with the JS in this particular case:
![image](https://user-images.githubusercontent.com/875568/201423699-244dd807-418f-4dce-a503-dd1898cbf88c.png)

The more complex case from my toy database looks like this:

![image](https://user-images.githubusercontent.com/875568/201424214-9d2181e2-5560-4cad-a47e-467a748c309f.png)

I'm rather curious as to why the "Get" was allowed to run during the "Put" and even the "Put" can overlap with another. 
BTW I also suspect a clock resolution / backward movement issue with `time.Now` here...

EDIT: this also happens with a simple `sync.Mutex`.

Let me know what you think, especially if I screwed up the model somehow.

**Comment by anishathalye** [comment] 2022-11-14 03:41
The issue is with the model. (re-attaching your original `model.go` here in case anyone wants to refer to it in the future).

<details>
<summary>(hidden, click to expand)</summary>

```go
package rwlock

import (
	"fmt"
	"github.com/anishathalye/porcupine"
	"reflect"
)

const (
	GetOp = iota
	PutOp = iota
	DelOp = iota
)

type Input struct {
	Operation uint8
	Key       int
	Val       int
}

type Output struct {
	Key   int
	Val   int
	Found bool
}

type State struct {
	state map[int]int
}

var Model = porcupine.Model{
	Init: func() interface{} {
		return State{
			state: map[int]int{},
		}
	},
	Step: func(state interface{}, input interface{}, output interface{}) (bool, interface{}) {
		s := state.(State)
		i := input.(Input)
		o := output.(Output)

		stateVal, found := s.state[i.Key]

		switch i.Operation {
		case GetOp:
			if !o.Found {
				return !found, s
			} else if stateVal == o.Val {
				return true, s
			}
			break
		case PutOp:
			s.state[i.Key] = i.Val
			return true, s
		case DelOp:
			delete(s.state, i.Key)
			return true, s
		}

		return false, s
	},
	Equal: func(a, b interface{}) bool {
		return reflect.DeepEqual(a, b)
	},
	DescribeOperation: func(input interface{}, output interface{}) string {
		i := input.(Input)
		o := output.(Output)

		opName := ""
		switch i.Operation {
		case GetOp:
			opName = "Get"
			break
		case PutOp:
			opName = "Put"
			break
		case DelOp:
			opName = "Del"
			break
		}

		return fmt.Sprintf("%s(%d) -> %d", opName, i.Key, o.Val)
	},
	DescribeState: func(state interface{}) string {
		s := state.(State)
		return fmt.Sprintf("%v", s.state)
	},
}
```

</details>

The problem is that `Model.Step` violates the contract that `Step` should be a pure function. (This isn't explained clearly in the docs, so I'll work on improving the documentation on this.)

Fixing that:

```diff
diff --git i/rwlock/model.go w/rwlock/model.go
index 29ca178..6eba91c 100644
--- i/rwlock/model.go
+++ w/rwlock/model.go
@@ -28,6 +28,15 @@ type State struct {
 	state map[int]int
 }
 
+func (st State) Clone() State {
+	var st2 State
+	st2.state = make(map[int]int)
+	for k, v := range st.state {
+		st2.state[k] = v
+	}
+	return st2
+}
+
 var Model = porcupine.Model{
 	Init: func() interface{} {
 		return State{
@@ -35,7 +44,7 @@ var Model = porcupine.Model{
 		}
 	},
 	Step: func(state interface{}, input interface{}, output interface{}) (bool, interface{}) {
-		s := state.(State)
+		s := state.(State).Clone()
 		i := input.(Input)
 		o := output.(Output)
```

Now, it seems to pass:

```console
$ go test -v
=== RUN   TestHappyPath
--- PASS: TestHappyPath (0.00s)
=== RUN   TestMultiGoroutines
--- PASS: TestMultiGoroutines (3.34s)
PASS
ok      github.com/anishathalye/porcupine/rwlock        3.470s
```

I'm guessing that the borked visualization was due to the buggy `Model.Step`, but if you're still seeing buggy visualizations, please let me know, I would like to debug it.

**Comment by anishathalye** [comment] 2022-11-14 03:43
Also, btw, you'll get much better perf by partitioning the linearizability check by key, and then having the (per-key) model be just a register (i.e., a single value), like this: https://github.com/anishathalye/porcupine/blob/7cbc8342681863b08e96432402d0588fc1defa88/porcupine_test.go#L1141

**Comment by anishathalye** [comment] 2022-11-14 05:16
I updated the [documentation for Model](https://pkg.go.dev/github.com/anishathalye/porcupine#Model); happy to hear any improvements you can suggest to the wording.

**Comment by tjungblu** [comment] 2022-11-14 14:36
I've done a first attempt at moving to generics and adding the state cloning in #12, let me know what you think.

**Closed** 2022-11-15 21:30 UTC
